#!/bin/bash

sudo apt -y update

sudo apt install -y apt-transport-https ca-certificates curl software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable"

sudo apt -y update

sudo apt-cache policy docker-ce

sudo apt -y install docker-ce

sudo usermod -aG docker ${USER}

docker pull ubuntu
